INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast food');
INSERT INTO unit_of_meassure (description) VALUES ('Pound');
INSERT INTO unit_of_meassure (description) VALUES ('Tbsp');
INSERT INTO unit_of_meassure (description) VALUES ('Cups');
INSERT INTO unit_of_meassure (description) VALUES ('Cloves');
INSERT INTO unit_of_meassure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_meassure (description) VALUES ('Dash');